### PR TITLE
Add scrape interval to all metric sources

### LINKED ISSUE #84: Add scrape intervals to each metric?
I've heard that there was confusion over the default scrape interval being used when scraping metrics.

The default is `60s`, which is set in [prometheus.scrape](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.scrape/#arguments). However, a user not familiar with flow might not know that is the default. They wouldn't necessarily know to dig down into agent documentation.

If we set:
```
node-exporter:
  scrapeInterval: 60s
```

And use that in the generated config, it would make it explicit.

### PR DESCRIPTION
**Pull request by petewall**
Fixes #84

### CODE REVIEW

**Review by jewbetcha — APPROVED** [review]
LGTM 👍 IIRC the scrape config as it exists out in the wild right now is 30s? maybe we should advise an update after this goes out

**Comment by petewall** [comment]
> IIRC the scrape config as it exists out in the wild right now is 30s?

Actually, this effectively is a no-op. Grafana agent's default scrape interval is 60s (https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.scrape/#arguments), not 30s. We're just pulling that variable up a layer to make it easier to override.

**Comment by jewbetcha** [comment]
Ah ok, maybe I was thinking about something else that caused our scrapes to increase. Sounds good.

**Comment by rknightion** [comment]
@petewall would it be possible to run the create-release ci? - Looks like although the chart ver was updated with this PR a release wasn't cut

**Comment by petewall** [comment]
Thanks for the poke. Yep, it's done now.

**Pull request merged**
