### PR TITLE
Support sending native histograms with remote_write

### PR DESCRIPTION
**Pull request by aptomaKetil**
Expose this setting under `externalServices.prometheus`, for backends that support it.

### CODE REVIEW

**Comment by petewall** [comment]
Thanks for creating this!
Make sure to run `make regenerate-example-outputs` and add the changes from that. That should get the failing tests to pass.

**Comment by aptomaKetil** [comment]
MacOS, was using Helm v3.9. Updated to v3.14 now and regenerated, and that got rid of the extra annotations.

**Review by petewall — APPROVED** [review]

**Comment by petewall** [comment]
That really helps! Thanks. You're the second person who had issues with this.

**Comment by petewall** [comment]
Your PR has been merged. Thanks for the contribution!!

**Pull request merged**
