### PR TITLE
Add the ability to set extraMetricProcessingRules for cadvisor

### PR DESCRIPTION
**Pull request by fplantinga-guida**

### CODE REVIEW

**Comment by fplantinga-guida** [comment]
@petewall, any idea how to fix the pipeline? I have run make build and make test locally, but this doesn't trigger any changes other than building the helm dependencies.

**Comment by fplantinga-guida** [comment]
@petewall, any updates on this?

**Comment by petewall** [comment]
Why don't I try and remake this change and I'll make sure you get co-author credit. Give me a bit.

**Comment by petewall** [comment]
Fixed in https://github.com/grafana/k8s-monitoring-helm/pull/924

**Pull request closed without merging**
