### PR TITLE
Make secret creation optional

### PR DESCRIPTION
**Pull request by davhdavh**
Sealed secrets or secrets operators require you create operators that will ultimately create the secret for you. Support that flow in the helm by making it optional to create the secret with credentials

### CODE REVIEW

**Comment by davhdavh** [comment]
@petewall did you miss this one?

**Comment by skl** [comment]
Hi @davhdavh thanks for all the contributions! We'll get back to you with some feedback after the weekend.

**Review by petewall — APPROVED** [review]
I like this a lot. Thanks.
Make sure to bump the version number and re-run helm-docs.

**Comment by marioanton** [comment]
really looking forward to this.

**Comment by petewall** [comment]
This should be complete now, as you can use external secrets. Feel free to open an issue if something is not working as expected.

**Pull request closed without merging**
