### PR TITLE
docs: add opencost custom secret info to readme (#285)

### PR DESCRIPTION
**Pull request by mischavandenburg**
To make it clearer that custom secrets can be used with Opencost, I added the values to the readme.

### CODE REVIEW

**Review by petewall — CHANGES_REQUESTED** [review]
Actually, `README.md` is automatically generated, using [helm-docs](https://github.com/norwoodj/helm-docs), from a combination of the built-in values.yaml, Chart.yaml, and README.md.gotmpl.

To make the changes you want the persistent way:
1. Edit values.yaml and remove the `# @ignored -- This skips including these values in README.md` fields before the OpenCost secret fields
2. Update the comments with your descriptions
3. Run `cd charts/k8s-monitoring && make README.md`

**Comment by petewall** [comment]
Merged it in with this PR: https://github.com/grafana/k8s-monitoring-helm/pull/306

**Comment by mischavandenburg** [comment]
Thank you for updating it and your explanation @petewall! Sorry I didn't get around to it but maybe I can contribute with something else in the future.

**Comment by petewall** [comment]
No problem! It was a good idea to put in the docs and I had a bit of time to pull things in.
I appreciate the issue and your original PR!

**Pull request closed without merging**
